package max.nlp.wrappers.berkeley;

import java.util.Comparator;
import java.util.function.Function;
import java.util.function.ToDoubleFunction;
import java.util.function.ToIntFunction;
import java.util.function.ToLongFunction;

public class WordAlignmentComparator implements Comparator<WordAlignment>{

	public int compare(WordAlignment arg0, WordAlignment arg1) {
		return arg0.geteIndex().compareTo(arg1.geteIndex());
	}

	
	//WARNING
	//The code below was autogenerated by eclipse, and doenst work. It is just there because java8 requires it
	
	public Comparator<WordAlignment> reversed() {
		// TODO Auto-generated method stub
		return null;
	}

	public Comparator<WordAlignment> thenComparing(
			Comparator<? super WordAlignment> other) {
		// TODO Auto-generated method stub
		return null;
	}

	public <U> Comparator<WordAlignment> thenComparing(
			Function<? super WordAlignment, ? extends U> keyExtractor,
			Comparator<? super U> keyComparator) {
		// TODO Auto-generated method stub
		return null;
	}

	public <U extends Comparable<? super U>> Comparator<WordAlignment> thenComparing(
			Function<? super WordAlignment, ? extends U> keyExtractor) {
		// TODO Auto-generated method stub
		return null;
	}

	public Comparator<WordAlignment> thenComparingInt(
			ToIntFunction<? super WordAlignment> keyExtractor) {
		// TODO Auto-generated method stub
		return null;
	}

	public Comparator<WordAlignment> thenComparingLong(
			ToLongFunction<? super WordAlignment> keyExtractor) {
		// TODO Auto-generated method stub
		return null;
	}

	public Comparator<WordAlignment> thenComparingDouble(
			ToDoubleFunction<? super WordAlignment> keyExtractor) {
		// TODO Auto-generated method stub
		return null;
	}

	public static <T extends Comparable<? super T>> Comparator<T> reverseOrder() {
		// TODO Auto-generated method stub
		return null;
	}

	public static <T extends Comparable<? super T>> Comparator<T> naturalOrder() {
		// TODO Auto-generated method stub
		return null;
	}

	public static <T> Comparator<T> nullsFirst(Comparator<? super T> comparator) {
		// TODO Auto-generated method stub
		return null;
	}

	public static <T> Comparator<T> nullsLast(Comparator<? super T> comparator) {
		// TODO Auto-generated method stub
		return null;
	}

	public static <T, U> Comparator<T> comparing(
			Function<? super T, ? extends U> keyExtractor,
			Comparator<? super U> keyComparator) {
		// TODO Auto-generated method stub
		return null;
	}

	public static <T, U extends Comparable<? super U>> Comparator<T> comparing(
			Function<? super T, ? extends U> keyExtractor) {
		// TODO Auto-generated method stub
		return null;
	}

	public static <T> Comparator<T> comparingInt(
			ToIntFunction<? super T> keyExtractor) {
		// TODO Auto-generated method stub
		return null;
	}

	public static <T> Comparator<T> comparingLong(
			ToLongFunction<? super T> keyExtractor) {
		// TODO Auto-generated method stub
		return null;
	}

	public static <T> Comparator<T> comparingDouble(
			ToDoubleFunction<? super T> keyExtractor) {
		// TODO Auto-generated method stub
		return null;
	}

}
